start_year = 1900
end_year = 2000

MONTH_DAYS=[31,29,31,30,31,30,31,31,30,31,30,31]
FEBRURARY = 1

## check all candidates generated by masks
## add --stdout to hashcat command

for month in range(len(MONTH_DAYS)):
    max_day = MONTH_DAYS[month]
    for day in range(max_day):
        real_month = month+1
        real_day = day+1
        if(real_month>=1 and real_month<=9 and real_day>=1 and real_day<=9):continue
        if(real_month>=1 and real_month<=9 and real_day>=11 and real_day<=19):continue
        if(real_month>=1 and real_month<=9 and real_day>=21 and real_day<=29):continue
        

        if(real_month>=10 and real_month<=12 and real_day>=1 and real_day<=9):continue
        if(real_month>=10 and real_month<=12 and real_day>=11 and real_day<=19):continue
        if(real_month>=10 and real_month<=12 and real_day>=21 and real_day<=29):continue
        
        if(real_month>=1 and real_month<=9 and (real_day==10 or real_day==20)):continue
        if(real_month>=1 and real_month<=9 and (real_day==10 or real_day==20)):continue

        if(real_month>=10 and real_month<=12 and (real_day==10 or real_day==20 or real_day==30)):continue
        
        if(real_month>=1 and real_month<=9 and real_month!=2 and real_day==30):continue

        if((real_month==1 or real_month==3 or real_month==5 or real_month==7 or real_month==8 )and real_day==31):continue
        
        if((real_month==10 or real_month==12 )and real_day==31):continue
       

        pesel_day = "%02d%02d"%(real_month, real_day)
        print("012,?d?d"+pesel_day+"?1"+4*"?d")


FULL = True

def save(alph, mask):
    if FULL:
         print(alph+",?d?d"+mask+"?1?d?d?d?d")
    else:
        print(alph+","+mask)
    
       
# full mask print("012,123456789,012,?d?d"+"0?2?3?2"+"?1"+4*"?d")


# rule for month from 1-9 day 1-9
#print("012,123456789,?d?d"+"0?20?2"+"?1"+4*"?d")
# rule for month from 1-9 day 11-19
#print("012,123456789,?d?d"+"0?21?2"+"?1"+4*"?d")
# rule for month from 1-9 day 21-29
#print("012,123456789,?d?d"+"0?22?2"+"?1"+4*"?d")
save("012,123456789,012", "0?2?3?2")

# rule for month from 10-12 day 1-9
#save("012,123456789,012", "1?30?2")
# rule for month from 10-12 day 11-19
#save("012,123456789,012", "1?31?2")
# rule for month from 10-12 day 21-29
#save("012,123456789,012", "1?32?2")

save("012,123456789,012", "1?3?3?2")


# rule for month from 10-12 day 10,20,30
save("012,012,123", "1?2?30")

# rule for month from 1,3,4,5,6,7,8,9 day 30
save("012,13456789","0?230")

# rule for month from 1,3,5,7,8 day 31
save("012,13578", "0?231")

# rule for month from 10,12 day 31
save("012,02", "1?231")

# rule for month from 1-9 day 10,20
save("012,123456789,12","0?2?30")

